package com.recomo.common.controller

data class ControllerState(
    val leftX: Float = 0f,
    val leftY: Float = 0f,
    val rightX: Float = 0f,
    val rightY: Float = 0f,
    val l2: Float = 0f,
    val r2: Float = 0f,
    val hatX: Float = 0f,
    val hatY: Float = 0f,
    val a: Boolean = false,
    val b: Boolean = false,
    val x: Boolean = false,
    val y: Boolean = false,
    val l1: Boolean = false,
    val l2Button: Boolean = false,
    val r1: Boolean = false,
    val r2Button: Boolean = false,
    val l3: Boolean = false,
    val r3: Boolean = false,
    val select: Boolean = false,
    val start: Boolean = false,
    val home: Boolean = false,
    val turbo: Boolean = false,
    val m1: Boolean = false,
    val m2: Boolean = false,
    val dpadUp: Boolean = false,
    val dpadDown: Boolean = false,
    val dpadLeft: Boolean = false,
    val dpadRight: Boolean = false,
    val lastKeyCode: Int? = null,
    val lastKeyName: String? = null,
    val lastKeyScanCode: Int? = null,
    val lastKeyAction: Int = -1,
    val lastKeyEventAtMs: Long = 0L,
    val timestampMs: Long = 0L
)
